version: '3'
services:
  db:
    image: postgres
    container_name: server-side-image-db
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: your_password
      POSTGRES_USER: your_username
      POSTGRES_DB: your_database_name
    volumes:
      - ./pgdata/var/lib/postgresql/data
    ports:
      - "5432:5432" # Port PostgreSQL container di-mapping ke port 5432 pada host
  app:
    image: server-side-image
    container_name: server-side-image-app
    build: .
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    env_file:
      - .env
    environment:
      - JWT_SECRET
    ports:
      - "8000:8000" # Port aplikasi container di-mapping ke port 8000 pada host
    depends_on:
      - db # Menunggu service "db" untuk siap sebelum menjalankan service "app"
volumes:
  node_modules: